# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Use Python 3.8'

- script: |
    curl -sSL https://raw.githubusercontent.com/python-poetry/install.python-poetry.org/main/install-poetry.py | python -
    export PATH=$PATH:$HOME/.poetry/bin
    poetry install --no-root
  displayName: 'Install dependencies'

- script: echo "##vso[task.prependpath]$HOME/.poetry/bin"
  displayName: Add poetry to PATH

- script: |
    poetry run pytest --alluredir=allure-results
  displayName: 'pytest'

- script: |
    wget https://github.com/allure-framework/allure2/releases/download/2.24.1/allure_2.24.1-1_all.deb
    sudo dpkg -i allure_2.24.1-1_all.deb
    allure generate
  displayName: install allure and generate allure report

# https://marketplace.visualstudio.com/items?itemName=MichaelClay.azure-pipelines-allure-report-viewer
- task: PublishAllureReport@1
  displayName: 'Publish Allure Report'
  inputs:
    reportDir: 'allure-report'
